In [104]:
import numpy as np
from collections import Counter
import Sudoku



def available_numbers(master, taken):
    master_arr = np.array([i for i in range(1, 10) for _ in range(9)])
    clue_arr = np.array([[1,2,3],[3,3,3],[3,3,3]]).flatten()
    clueCount = Counter(clue_arr)
    fullCount = Counter(master_arr)
    remainCount = fullCount - clueCount
    result = np.array([val for val, cnt in remainCount.items() for _ in range(cnt)])
    return result
    

class SimulatedAnnealing:
    def __init__(self, sudoku_init, t_sched = None):
        self.grid = np.array(sudoku_init.board)
        self.fixed = np.array(sudoku_init.fixed)
        self.can_swap = ~self.fixed
        self.possible_numbers = available_numbers(np.array([i for i in range(1, 10) for _ in range(9)]), self.grid.flatten())
        self.populate()
        
        
        
    def populate(self):
        poss_nums = self.possible_numbers.copy()
        np.random.shuffle(poss_nums)
        mask = self.can_swap.copy()
        mask.flatten()
        expanded = np.zeros(mask.shape, dtype=int)
        #self.grid[self.can_swap] = poss_nums
        expanded[mask] = poss_nums[:mask.sum()]
        self.grid+=expanded
        print(self.grid)
        
    def swap(self):
        pass
        
        

In [111]:
import Sudoku

board1 = Sudoku.Sudoku(3)
digitString = "070000043040009610800634900094052000358460020000800530080070091902100005007040802"
board1.fillFromString(digitString)
SimulatedAnnealing(board1)

[[5 7 4 2 5 3 1 4 3]
 [6 4 9 7 7 9 6 1 6]
 [8 1 4 6 3 4 9 7 1]
 [2 9 4 3 5 2 7 8 2]
 [3 5 8 4 6 9 7 2 5]
 [8 9 8 8 2 2 5 3 6]
 [6 8 8 5 7 5 7 9 1]
 [9 2 2 1 4 4 2 1 5]
 [8 7 7 7 4 8 8 6 2]]


In [18]:
mask = np.array([True, False, True, True])
poss_nums = np.array([1,2,3])
expanded = np.zeros(mask.shape[0], dtype=int)
expanded[mask] = poss_nums[:mask.sum()]
print(expanded)

[1 0 2 3]
